name: Build Warp 10 docker image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Get Latest tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the image
        run: |
          docker buildx build --push \
            --tag stevengueguen/warp10:$TAG \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
        env:
          TAG: ${{ steps.lastest_tag.outputs.tag }}
