name: Build Warp 10 docker image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Get Latest tag
        id: latest_tag
        run: echo ::set-output name=TAG::$(git describe --abbrev=0 --tags)

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the image
        run: |
          docker buildx build --push \
            --tag stevengueguen/warp10:$TAG \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
        env:
          TAG: ${{ steps.latest_tag.outputs.tag }}
