name: Build Warp 10 docker image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all branches and tags so we can find the latest tag

      - name: Get latest tag
        run: echo "::set-env name=TAG::$(git describe --abbrev=0 --tags)"

      - name: Set up Docker Buildx for multiarch build
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the main image
        run: |
          for ARCH in amd64 arm/v7 arm64; do
            docker buildx build
              --load
              --tag ${{ secrets.DOCKER_USERNAME }}/warp10:${TAG} \
              --platform linux/${ARCH} .
          done
          
      - name: Build the ci image
        run: |
          docker buildx build \
            --tag ${{ secrets.DOCKER_USERNAME }}/warp10:${TAG}-ci \
            --platform linux/amd64,linux/arm/v7,linux/arm64 predictible-tokens-for-ci

      - name: Tag image
        run: docker tag warp10io/warp10:${TAG} warp10io/warp10; echo $(docker images)

      - name: Push image if new tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Push on new tag";
